### ISSUE TITLE
[低優先] 機能要望: 閲覧履歴機能のON/OFF

### ISSUE THREAD

**Issue by yasokada** [howdy39/q-accelerator#133]
**概要**

「閲覧履歴」の項目がありますが、閲覧履歴機能のON/OFFも選択できれば、と思いました。

**環境**

- **Q Accelerator Version: 1.0.0**
- **Chrome Version: 55.0.2883.87 m**
- **OS: Windows 8.1 pro (64bit)**

**Comment by howdy39** [comment]
こっちにも登録してくれたんですね。
ありがとうございます。

次バージョンに含めたいと思います。

**Comment by yasokada** [comment]
ご対応ありがとうございました。
