### ISSUE TITLE
行番号表示時のコピーの動作違いについて

### ISSUE THREAD

**Issue by jh1cdv00** [howdy39/q-accelerator#134]
**概要**
素晴らしい機能ありがとうございます、行番号がついて見やすくなりました。
自分は、qiitaの情報を、onenoteにコピーして、活用させてもらっています。

ただ、コピーした時、下記の様に違いがあります。
行番号表示時　：行番号しかコピーできない
行番号非表示時：コピーできる

onenoteのほうかもしれませんが、できれば、調べて、教えてもらえると助かります。

**環境**
バージョン 55.0.2883.87 m (64-bit)
Google Chrome は最新版です。

**エラーメッセージ**

申し訳ありませんが、エラーは、たくさん出ていて、動くとき、動かない時が、よくわかりませんでした？？？
VM101:61 Refused to connect to 'https://nikkomsgchannel/e?4' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com".```

```

**Comment by howdy39** [comment]
@jh1cdv00 

報告ありがとうございます。

そのエラーはQiita本体のエラーですね。（結構でるんですよね）

行番号とはいえコピーができているならQ Acceleratorのエラーメッセージは出なそうです。
原因は不明ですがコピーする対象が行番号にずれちゃっているんだと思います。

動くとき、動かないときというのは同じコードに対して変わるということでしょうか？
それともこのコードだと動くけど、こっちのコードだと動かない、みたいな感じでしょうか？

**Comment by jh1cdv00** [comment]
nakanoさん

わざわざ、返信ありがとうございます。

＞動くとき、動かないときというのは同じコードに対して変わるということでしょうか？
はい、同じｗｅｂのページに対して、行番号機能を ＯＮ/ＯＦＦして確認しました。

簡単に、ＯＮ/ＯＦＦ出来るので、たいしたことないといえばないのですが・・・

簡単に、ＯＮ/ＯＦＦ出来るのも、良い機能ですね、目的が違うのかもしれませんが、
助かります。

松元

2017年1月10日 9:15 Tatsuya Nakano <notifications@github.com>:

**Comment by howdy39** [comment]
@jh1cdv00

返信ありがとうございます。

根本原因はよくわからなかったのですが、なおりそうな感じに修正しました。

今週末ぐらいに拡張機能を更新します。
バージョンがあがっても再度起こるようでしたら、ここにその旨コメントするか別のIssueたててください。
