### ISSUE TITLE
コピーアイコンが文字に被るケースがある

### ISSUE THREAD

**Issue by KeisukeKudo** [howdy39/q-accelerator#142]
**概要**

行番号非表示､コピーアイコンを表示に設定するとアイコンが文字に被るケースがあります｡  

>\`\`\`title
>foo
>\`\`\`  

タイトルがある場合は問題ないのですが  

>\`\`\`
>foo
>\`\`\`  

のようにタイトルがない場合コピーアイコンが文字に被って表示されてしまいます｡

![icon](https://raw.githubusercontent.com/KeisukeKudo/ImageStorage/master/2017-01-11-18-51.png)

既知の問題かとも思いましたが､念の為共有致します｡

**環境**

- **Q Accelerator Version: 1.0.0**
- **Chrome Version: 57.0.2977.0 canary (64-bit)**

**Comment by howdy39** [comment]
それは不具合ですね。

タイトルがないときにはコード上部に余白でも入れちゃおうかと思います。
![image](https://cloud.githubusercontent.com/assets/6329532/21846532/ede3b8c0-d83a-11e6-9421-fdc0b9d63fec.png)

ご報告ありがとうございました。
