### ISSUE TITLE
ストック数を見れるようにする

### ISSUE THREAD

**Issue by elysion-halcyon** [howdy39/q-accelerator#152]
機能提案
---
以前のQiitaでは表示されていたが現UIでは表示されない、ストック数が見たい

備考
---
ストック数を見れるChrome拡張QiitaStockWatcherが既に存在する。
[Qiitaの「いいね」に消された「ストック数」を復活させた - Qiita](http://qiita.com/hikarut/items/c71063af8cb79124de72)
が、このChrome拡張はストア上にないため、セキュリティの都合上Chromeに無効化される(または無効化されないインストールに手間が発生する)。

**Comment by howdy39** [comment]
提案ありがとうございます。

IP毎のリクエスト制限が気になったのですが
（職場とかで複数人が使ってたらすぐ使えなくなるかも）
次バージョンで実験的に入れてみようと思います。

**Comment by howdy39** [comment]
1週間以内にUPします。
