### ISSUE TITLE
記事の更新日を時間まで表示できるようにする

### ISSUE THREAD

**Issue by elysion-halcyon** [howdy39/q-accelerator#158]
記事ページ左上の「2017年02月07日に更新」のように投稿・更新日が表示されている部分で、
特に新しい記事においては年月日だけでなく時間まで確認したいと思うことがある。

```html
<time datetime="2017-02-07T20:46:32+09:00" itemprop="dateModified">2017年02月07日</time>
```
のように、時間のデータは持っているようす。

**Comment by howdy39** [comment]
提案ありがとうございます。

入れるとしたら時分までが良さそうでしょうか。

<img width="488" alt="2017-02-10 23 26 42" src="https://cloud.githubusercontent.com/assets/6329532/22830058/89eea1ca-efe8-11e6-90e2-76c1a12b0141.png">
