### ISSUE TITLE
機能 > 新規投稿時のテンプレート > 保存・読込

### ISSUE THREAD

**Issue by yasokada** [howdy39/q-accelerator#159]
**概要**

[希望]
異なるOS間において、「新規投稿時のテンプレート」の設定を共有したい。

[現状]
新規投稿時のテンプレートを変更後、Qiitaの下書きを使ってそのテンプレートを保存し、
その下書きを用いて、他のOS上のテンプレートを更新しています。
使用中の7つのOS環境において、上記のような作業が、「ごくたまに」発生することがあります。

可能かどうか分かりませんが「保存」「読込」ボタンにより、テンプレートの保存と読込み
ができればと思います。
問題はそういう設定をどこに置けばいいのか、が分かりませんが。

1. Export / Importでファイル共有 (Qiitaの下書きやメモファイルとの違いは?)
2. Dropbox経由 (Dropboxユーザでないといけない)
3. Qiita API? (限定公開記事?)
4. その他、なんらかの個人アカウントに結びつくもの

**環境**

- **Q Accelerator Version: v1.2.0**
- **Chrome Version: 56.0.2924.87**
- **Windows 7 Pro(32bit) / Windows 8.1 Pro(64bit) / Windows 10 Pro (64bit) / OS X El Capitan **
 (CentOS 6.5, Ubuntu 14.04 LTS上でも使う予定)

**Comment by howdy39** [comment]
提案ありがとうございます。
テンプレート設定を複数端末で共有したい、自動反映して欲しい、ってことですよね。

以下の仕様でどうでしょうか。

# 仕様
1. Dropbox（公開リンク）やGist（非公開）とかにテンプレートファイルをupする。
  ※Gistの場合、直接読めないのでRawiGitをかませる。
2. 設定画面では、今までの直接入力の他にURL指定が出来るようにする。
3. 上記URL指定欄に1のURLを記入。
4. 下書きページを開いた際に入力したURLからテンプレートを読み込む。

※リンクがわかれば誰でも見れちゃうので本当に漏れたらまずい情報は記載してはダメです。（拡張機能にそんなこと書く人はいないと思いますが）


# URL例

## Dropbox
https://dl.dropboxusercontent.com/u/35899471/template.md

## Gist + Rawgit
https://cdn.rawgit.com/howdy39/4e7a3290bd4ba9ebbe46f2cd394d0ffd/raw/9c97bf17505b4a2f491a60351cfae814f92fc54d/temlate.md

**Comment by yasokada** [comment]
@howdy39 

仕様のご検討ありがとうございます。

僕が考えていましたのは、テンプレートの情報を共有して「直接入力」を書き換えする方法でした。
「URL指定」の方ですと、複数のテンプレートを切り替えすることもでき、使い勝手がいいように思います。

いい考えだと思います。
また、その機能の実装方法もすでに（２つ）ご存じなのですね。

> ※リンクがわかれば誰でも見れちゃうので本当に漏れたらまずい情報は記載してはダメです。

確かにです。Qiita用の下書きで個人情報を書く人はいないと思いますが、気を付けないといけないですね。

**Comment by yasokada** [comment]
お疲れ様です。

**Comment by howdy39** [comment]
@yasokada 
本件、リリースしました。

**Comment by yasokada** [comment]
@howdy39 
使い始めました。

ご用意されたhow-to-create-article-template-url.mdに従い使用できました。こういうドキュメントがあるのはありがたいです。

これで、新規投稿時のテンプレート編集が気軽にできるようになります。

ありがとうございました。
