### ISSUE TITLE
不具合 > 数式表示時に左側に数字(例: 1234...)が表示される

### ISSUE THREAD

**Issue by yasokada** [howdy39/q-accelerator#171]
**概要**

数式を表示時に左側に数字(例: 1234...)が表示されます。

**環境**

- **Q Accelerator Version:1.3.1**
- **Chrome Version:57.0.2987.98**
- **OS: Windows 8.1 Pro (64bit)**
- **OS: Ubuntu 14.04 LTS desktop amd64**

**エラーメッセージ**

例として以下の記事をご確認ください。
[statistics > mean size and variance > 緯度経度ごとの値から緯度のmeanとvarianceを求める](http://qiita.com/7of9/items/fb5ad0130994a0629064)

コードの行表示に関して、行番号がmathの解析時にそのまま数字になっているようです。
しかしながら、これはQ Accelerator 側で対処できる問題なのかは不明です。
(Qiita側の数式解析処理と関連するような気もします。)

math形式の場合はコード行を表示しない、という方法で回避できるかもしれません。

**Comment by howdy39** [comment]
@yasokada 
不具合報告ありがとうございます。助かります。

> math形式の場合はコード行を表示しない、という方法で回避できるかもしれません。

これで対応します。

**Comment by howdy39** [comment]
v1.3.2で対応済み

**Comment by yasokada** [comment]
早速のご対応ありがとうございました。
