### ISSUE TITLE
ヘッダー固定機能が一部のページで動作していない

### ISSUE THREAD

**Issue by munierujp** [howdy39/q-accelerator#200]
Qiitaのトップページが微妙にリニューアルされた結果、一部のページでヘッダー固定機能が動作しなくなっています。

* [トレンド](https://qiita.com/)
* [マイルストーン](https://qiita.com/milestones)

`fix-header.js`ファイルの`URL_PATTERN_TOP`を`new RegExp(''^https?://qiita\\.com(/(timeline|tag-feed|milestones))?$');`などに変更すればよさそうです。

**Comment by yuta0801** [comment]
#199 で修正しました！

**Comment by howdy39** [comment]
ご報告＆PRありがとうございます。
今リリース中です！しばしおまちを
