### ISSUE TITLE
”後で読む”機能

### ISSUE THREAD

**Issue by yuta0801** [howdy39/q-accelerator#205]
Webサイト全般で使えるサービス、ツールなどもいくつか存在しているので実際に必要とされているかはわかりませんが、自分の場合はうまく管理出来ていないのでQiita内で操作できるように後で読む機能があるといいと思いました

具体的な動作：
内部的には履歴と同様の実装(ストレージ+オプション画面のタブ)で、
追加/削除はQiitaにあるストックボタンのような形に。
追加時にはその下のコメント、ソーシャルアイコンのような形で後で読むリストを前後できるボタンも追加。
読み終わったときに後で読むをはずし移動することも考えて外しても要素の削除は行わない。

**Comment by howdy39** [comment]
なるほど、`Pocket` や `はてブ` じゃうまく管理できてないってことですよね。

`q-accelerator` がやるのとはちょっと違う気がします。
※Qiita以外にもあとで読むが必要になるはずなので

そうなると、作るにしても別の拡張機能として作るほうが良いんじゃないでしょうか？

**Comment by yuta0801** [comment]
なるほど！そうしてみます！
